apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-auto-single-mem
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scaling-auto-single-mem
  template:
    metadata:
      name: scaling-auto-single-mem
      labels:
        app: scaling-auto-single-mem
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
      containers:
      - name: scaling-auto-single-mem-spec
        image: irfdocker/powershell:latest
        # refer https://docs.microsoft.com/en-us/sysinternals/downloads/testlimit
        command: ["testlimit64.exe"]
        args: ["-accepteula", "-d", "215", "-c", "1"]
        resources:
          limits:
            cpu: "0.1"
            memory: "256Mi"
          requests:
            cpu: "0.01"
            memory: "64Mi"
