apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-auto-single-cpu
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scaling-auto-single-cpu                           
  template:
    metadata:
      name: scaling-auto-single-cpu
      labels:
        app: scaling-auto-single-cpu
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
      containers:
      - name: scaling-auto-single-cpu-spec
        image: irfdocker/powershell:latest
        command: ["stress.exe"]
        # the cpuload is in cores
        # set it wrt the limits and requests for desired results
        args: ["cpu", "--cpuload", "0.1", "--duration", "8640000", "--cpucore", "0"]
        resources:
          limits:
            cpu: "0.1"
            memory: "256Mi"
          requests:
            cpu: "0.01"
            memory: "128Mi"
